# Generated by Django 3.0.4 on 2020-03-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='user',
        ),
    ]
