# Generated by Django 3.0.4 on 2020-03-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_school_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='established_date',
            field=models.DateField(),
        ),
    ]
