# Generated by Django 3.0.4 on 2020-03-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200319_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_mobile_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_telephone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
